version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    executor: python/default
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest
          name: pytest
workflows:
  main:
    jobs:
      - build

