title: trex
description: Templatosaurus Rex: Create and manage project templates in your terminal 🦖
logo: https://raw.githubusercontent.com/berrysauce/trex/master/docs/assets/img/logo.PNG
show_downloads: false
theme: jekyll-theme-minimal
